using EzCMS.Core.Framework.Attributes;
using System.ComponentModel;

namespace EzCMS.Core.Framework.Enums
{
    public enum EditorTool
    {
        [EditorToolSetting(EditorToolGroup.Document)]
        Source,
        [EditorToolSetting(EditorToolGroup.Document)]
        Save,
        [EditorToolSetting(EditorToolGroup.Document)]
        NewPage,
        //DocProps,
        [EditorToolSetting(EditorToolGroup.Document)]
        Preview,
        [EditorToolSetting(EditorToolGroup.Document)]
        Print,
        [EditorToolSetting(EditorToolGroup.Document)]
        Templates,
        //Document,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        Cut,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        Copy,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        Paste,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        PasteText,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        PasteFromWord,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        Undo,
        [EditorToolSetting(EditorToolGroup.Clipboard)]
        Redo,
        [EditorToolSetting(EditorToolGroup.Editing)]
        Find,
        [EditorToolSetting(EditorToolGroup.Editing)]
        Replace,
        [EditorToolSetting(EditorToolGroup.Editing)]
        SelectAll,
        [EditorToolSetting(EditorToolGroup.Editing)]
        Scayt,
        [EditorToolSetting(EditorToolGroup.Forms)]
        Form,
        [EditorToolSetting(EditorToolGroup.Forms)]
        Checkbox,
        [EditorToolSetting(EditorToolGroup.Forms)]
        Radio,
        [EditorToolSetting(EditorToolGroup.Forms)]
        TextField,
        [EditorToolSetting(EditorToolGroup.Forms)]
        Textarea,
        [EditorToolSetting(EditorToolGroup.Forms)]
        Select,
        [EditorToolSetting(EditorToolGroup.Forms)]
        Button,
        [EditorToolSetting(EditorToolGroup.Forms)]
        ImageButton,
        [EditorToolSetting(EditorToolGroup.Forms)]
        HiddenField,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        Bold,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        Italic,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        Underline,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        Strike,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        Subscript,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        Superscript,
        [EditorToolSetting(EditorToolGroup.BasicStyles)]
        RemoveFormat,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        NumberedList,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        BulletedList,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        Outdent,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        Indent,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        Blockquote,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        CreateDiv,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        JustifyLeft,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        JustifyCenter,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        JustifyRight,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        JustifyBlock,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        BidiLtr,
        [EditorToolSetting(EditorToolGroup.Paragraph)]
        BidiRtl,
        [EditorToolSetting(EditorToolGroup.Links)]
        Link,
        [EditorToolSetting(EditorToolGroup.Links)]
        Unlink,
        [EditorToolSetting(EditorToolGroup.Links)]
        Anchor,
        //CreatePlaceholder,
        [EditorToolSetting(EditorToolGroup.Insert)]
        Image,
        [EditorToolSetting(EditorToolGroup.Insert)]
        Flash,
        [EditorToolSetting(EditorToolGroup.Insert)]
        Table,
        [EditorToolSetting(EditorToolGroup.Insert)]
        HorizontalRule,
        [EditorToolSetting(EditorToolGroup.Insert)]
        Smiley,
        [EditorToolSetting(EditorToolGroup.Insert)]
        SpecialChar,
        [EditorToolSetting(EditorToolGroup.Insert)]
        PageBreak,
        [EditorToolSetting(EditorToolGroup.Insert)]
        Iframe,
        [EditorToolSetting(EditorToolGroup.Insert)]
        InsertPre,
        [EditorToolSetting(EditorToolGroup.Insert)]
        Youtube,
        [EditorToolSetting(EditorToolGroup.Insert)]
        FontAwesome,
        [EditorToolSetting(EditorToolGroup.Insert)]
        [Description("EzCMS Curlybracket")]
        ezcmswidget,
        [EditorToolSetting(EditorToolGroup.Styles)]
        Styles,
        [EditorToolSetting(EditorToolGroup.Styles)]
        Format,
        [EditorToolSetting(EditorToolGroup.Styles)]
        Font,
        [EditorToolSetting(EditorToolGroup.Styles)]
        FontSize,
        [EditorToolSetting(EditorToolGroup.Colors)]
        TextColor,
        [EditorToolSetting(EditorToolGroup.Colors)]
        BGColor,
        [EditorToolSetting(EditorToolGroup.Tools)]
        //UIColor,
        Maximize,
        [EditorToolSetting(EditorToolGroup.Tools)]
        ShowBlocks,
    }

    public enum EditorToolGroup
    {
        Document,
        Clipboard,
        Editing,
        Forms,
        BasicStyles,
        Paragraph,
        Links,
        Insert,
        Styles,
        Colors,
        Tools
    }
}
